--- 
backend: 
  branch: master
  name: git-gateway
collections: 
  - 
    create: true
    fields: 
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: Summary
        name: description
        widget: text
      - 
        default: layouts/post.njk
        label: Layout
        name: layout
        widget: hidden
      - 
        default: 
          - post
        label: Tags
        name: tags
        widget: list
      - 
        fields: 
          - 
            label: Key
            name: key
            widget: string
          - 
            label: Title
            name: title
            widget: string
          - 
            default: Sankatmochan
            label: Parent
            name: parent
            widget: string
          - 
            default: 0
            label: Order
            name: order
            widget: number
        label: Navigation
        name: eleventyNavigation
        widget: object
      - 
        label: Body
        name: body
        widget: markdown
    folder: posts
    label: Post
    name: blog
    slug: "{{slug}}"
  - 
    create: false
    fields: 
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: Permalink
        name: permalink
        widget: string
      - 
        label: Body
        name: body
        widget: markdown
    folder: pages
    label: Page
    name: pages
    slug: "{{slug}}"
media_folder: static/img
publish_mode: editorial_workflow
